import type { Department, Industry, PlaybookStep } from "@autonomos/schemas";

// The ready-made playbooks every new workspace can try: tool-neutral templates, each tagged with
// the industries it suits (a playbook can serve several). They are written into the database by
// a migration generated from this file (pnpm --filter @autonomos/integrations playbooks:sql), which
// never overwrites a playbook an administrator has since edited.

export type LibraryPlaybook = {
  slug: string;
  title: string;
  summary: string;
  department: Department;
  industries: Industry[];
  trigger: string;
  minutes: number;
  steps: PlaybookStep[];
  agent: {
    name: string;
    description: string;
    autonomyLevel: 2 | 3 | 4;
    objective: string;
    context: string;
    rules: string[];
    escalation: string[];
    success: string[];
  };
};

const ALL: Industry[] = [
  "SaaS & software",
  "Marketplaces",
  "E-commerce & D2C",
  "Media & publishing",
  "Agencies",
  "Recruitment & staffing",
  "Online education",
  "Travel & booking",
  "Property & rentals",
  "Fintech & insurance",
  "Professional services",
  "Other",
];

const read = (title: string, detail: string, capability: string | null): PlaybookStep => ({ title, detail, capability, access: "read" });
const write = (title: string, detail: string, capability: string | null): PlaybookStep => ({ title, detail, capability, access: "write" });
const decide = (title: string, detail: string): PlaybookStep => ({ title, detail, capability: null, access: "none" });

export const PLAYBOOK_LIBRARY: LibraryPlaybook[] = [
  // ---------------------------------------------------------------- shared across industries
  {
    slug: "library-invoice-chasing",
    title: "Invoice chasing",
    summary: "Reminds customers about overdue invoices on a fixed schedule and tells finance who still has not paid.",
    department: "Finance",
    industries: ALL.filter((i) => i !== "Travel & booking"),
    trigger: "An invoice passes its due date unpaid",
    minutes: 10,
    steps: [
      read("Find invoices past their due date", "List open invoices with a due date before today and no payment.", "accounting"),
      read("Check for a payment that has not been matched yet", "Look for a payment from the same customer for the same amount.", "payments"),
      decide("Pick the reminder for how late it is", "Friendly at 3 days, firm at 14 days, final notice at 30 days."),
      write("Send the reminder", "Email the billing contact with the invoice number, amount and a payment link.", "email"),
      write("Tell finance about invoices over 30 days late", "Post a short list with customer, amount and days overdue.", "chat"),
    ],
    agent: {
      name: "Invoice chasing",
      description: "Sends payment reminders for overdue invoices and escalates long-overdue ones.",
      autonomyLevel: 3,
      objective: "Get overdue invoices paid without anyone having to chase them by hand.",
      context: "Reminders go to the customer's billing contact. Finance decides on anything beyond reminders.",
      rules: ["Never send more than one reminder per invoice in 7 days", "Never threaten collection or legal steps", "Skip invoices that are disputed"],
      escalation: ["The customer disputes the invoice", "The invoice is over 60 days overdue", "The amount is above the approval limit"],
      success: ["Every overdue invoice got the right reminder", "Finance knows about every invoice over 30 days late"],
    },
  },
  {
    slug: "library-ticket-triage",
    title: "Support ticket triage",
    summary: "Reads each new ticket, tags its topic and urgency, and routes it to the right queue with a suggested reply.",
    department: "Customer Support",
    industries: ALL,
    trigger: "A new support ticket arrives",
    minutes: 4,
    steps: [
      read("Read the new ticket", "Subject, message and any attachments.", "helpdesk"),
      read("Look up the customer", "Plan, account status and recent tickets.", "crm"),
      decide("Decide topic, urgency and queue", "Billing, technical, account or other; urgent when a customer cannot work or pay."),
      write("Tag and route the ticket", "Set tags, priority and the queue or assignee.", "helpdesk"),
      write("Add a suggested reply as an internal note", "A draft the agent can send or edit.", "helpdesk"),
    ],
    agent: {
      name: "Ticket triage",
      description: "Tags, prioritises and routes new support tickets with a draft reply.",
      autonomyLevel: 4,
      objective: "Every new ticket reaches the right person, correctly prioritised, within minutes.",
      context: "Routing rules and queue names come from the help desk.",
      rules: ["Never reply to the customer directly", "Mark anything about security or data loss as urgent"],
      escalation: ["The ticket mentions a legal threat or a data breach", "The topic fits no queue"],
      success: ["Ticket tagged and routed", "Draft reply added as an internal note"],
    },
  },
  {
    slug: "library-refund-requests",
    title: "Refund and cancellation requests",
    summary: "Checks each refund or cancellation request against the policy and prepares the refund for approval.",
    department: "Customer Support",
    industries: ["E-commerce & D2C", "SaaS & software", "Travel & booking", "Online education", "Marketplaces", "Media & publishing", "Other"],
    trigger: "A customer asks for a refund or to cancel",
    minutes: 8,
    steps: [
      read("Read the request", "What is being refunded or cancelled, and why.", "helpdesk"),
      read("Find the payment", "The charge, its amount and date.", "payments"),
      decide("Check the refund policy", "Within the refund window, eligible reason, not refunded before."),
      write("Refund the payment", "Full or partial refund as the policy allows. A person approves above the limit.", "payments"),
      write("Reply and close the request", "Confirm the refund amount and when it arrives.", "helpdesk"),
    ],
    agent: {
      name: "Refund requests",
      description: "Handles refund and cancellation requests within the refund policy.",
      autonomyLevel: 3,
      objective: "Resolve eligible refund requests quickly and consistently with the policy.",
      context: "The refund policy sets the window and eligible reasons.",
      rules: ["Never refund more than the original charge", "Never refund a payment twice", "Refunds above the approval limit wait for a person"],
      escalation: ["The request is outside the refund window", "The customer has had more than two refunds this year", "Fraud is suspected"],
      success: ["Eligible requests refunded and answered", "Ineligible requests explained with the policy"],
    },
  },
  {
    slug: "library-lead-routing",
    title: "Inbound lead qualification",
    summary: "Qualifies each new inbound lead, enriches it, and routes it to the right owner the same day.",
    department: "Sales",
    industries: ["SaaS & software", "Agencies", "Professional services", "Property & rentals", "Recruitment & staffing", "Other"],
    trigger: "A new lead fills in a form or emails in",
    minutes: 12,
    steps: [
      read("Read the new lead", "Name, company, message and source.", "crm"),
      read("Check for an existing account or open deal", "Avoid duplicates and route to the current owner.", "crm"),
      decide("Score fit and intent", "Company size, need, budget signals and urgency."),
      write("Assign an owner and set the stage", "By territory or segment; qualified leads become a deal.", "crm"),
      write("Tell the owner", "Short summary with why the lead looks good.", "chat"),
    ],
    agent: {
      name: "Lead qualification",
      description: "Qualifies and routes inbound leads to the right owner.",
      autonomyLevel: 4,
      objective: "No good lead waits more than a few hours for an owner.",
      context: "Owners are assigned by territory or segment in the CRM.",
      rules: ["Never email the lead", "Never change an existing deal's owner"],
      escalation: ["The lead is a large company or partner", "The message is a complaint, not a sales enquiry"],
      success: ["Every lead has an owner and a stage", "The owner was told the same day"],
    },
  },
  {
    slug: "library-customer-onboarding",
    title: "New customer onboarding",
    summary: "Welcomes each new customer, checks setup steps are done, and nudges or flags the ones who stall.",
    department: "Customer Support",
    industries: ["SaaS & software", "Fintech & insurance", "Online education", "Agencies", "Other"],
    trigger: "A new customer signs up or signs the contract",
    minutes: 15,
    steps: [
      read("Get the new customer's details", "Plan, contact person and start date.", "crm"),
      write("Send the welcome email", "With the first steps and how to get help.", "email"),
      write("Book the kickoff call", "Offer times that suit the account owner.", "calendar"),
      read("Check setup progress after a week", "Which onboarding steps are done.", "crm"),
      write("Nudge or flag stalled customers", "A helpful reminder, or a note to the account owner.", "chat"),
    ],
    agent: {
      name: "Customer onboarding",
      description: "Guides new customers through their first weeks.",
      autonomyLevel: 3,
      objective: "Every new customer completes setup in their first two weeks.",
      context: "The onboarding checklist lives in the CRM.",
      rules: ["At most one nudge email per week", "Never promise features or discounts"],
      escalation: ["The customer is unhappy or asks to cancel", "No progress after two nudges"],
      success: ["Welcome sent and kickoff booked", "Stalled customers flagged to their owner"],
    },
  },
  {
    slug: "library-document-chasing",
    title: "Document chasing",
    summary: "Collects missing documents (contracts, certificates, ID checks) with polite reminders until the file is complete.",
    department: "Operations",
    industries: ["Fintech & insurance", "Recruitment & staffing", "Property & rentals", "Professional services", "Other"],
    trigger: "A file is missing a required document",
    minutes: 10,
    steps: [
      read("List files with missing documents", "Which documents each file still needs.", "documents"),
      write("Request the missing documents", "Email listing exactly what is needed and how to send it.", "email"),
      read("Check what came back", "Match received documents to the file.", "documents"),
      write("File the documents and update the checklist", "Mark each item received.", "documents"),
      write("Flag files still incomplete after two reminders", "To the person responsible.", "chat"),
    ],
    agent: {
      name: "Document chasing",
      description: "Requests and files missing documents until each file is complete.",
      autonomyLevel: 3,
      objective: "Complete files without anyone chasing documents by hand.",
      context: "Back-office only: the agent collects and files documents, a person reviews their content.",
      rules: ["Never judge whether a document is valid", "Never ask for documents the checklist does not require", "At most two reminders a week"],
      escalation: ["A document looks altered or does not match the person", "The person refuses or asks why"],
      success: ["Requested documents filed", "Incomplete files flagged after two reminders"],
    },
  },
  {
    slug: "library-failed-payment-recovery",
    title: "Failed payment recovery",
    summary: "Follows up failed card payments with clear, timed reminders until the payment method is updated.",
    department: "Finance",
    industries: ["SaaS & software", "Media & publishing", "Fintech & insurance", "Online education"],
    trigger: "A recurring payment fails",
    minutes: 6,
    steps: [
      read("Read the failed payment", "Customer, amount and why it failed.", "payments"),
      write("Email the customer to update their card", "With a secure update link.", "email"),
      read("Check whether the retry succeeded", "After the next scheduled retry.", "payments"),
      write("Send a final notice before the subscription pauses", "Clear date and what happens next.", "email"),
      write("Tell the account owner about high-value accounts", "Before access is lost.", "chat"),
    ],
    agent: {
      name: "Payment recovery",
      description: "Recovers failed recurring payments with timed reminders.",
      autonomyLevel: 4,
      objective: "Recover failed payments before customers lose access.",
      context: "Payment retries are scheduled by the payment system.",
      rules: ["Never charge the card manually", "Never change the subscription"],
      escalation: ["The customer replies with a complaint", "The account pays above the high-value threshold"],
      success: ["Customer told within a day of the failure", "High-value accounts flagged"],
    },
  },

  // ---------------------------------------------------------------- SaaS & software
  {
    slug: "library-trial-follow-up",
    title: "Trial-to-paid follow-up",
    summary: "Follows up trial users based on how much they used the product, and flags the hottest trials to sales.",
    department: "Sales",
    industries: ["SaaS & software"],
    trigger: "A trial is three days from ending",
    minutes: 8,
    steps: [
      read("List trials ending soon", "Trial end date, plan and contact.", "crm"),
      decide("Group trials by activity", "Active, light use, or no use."),
      write("Send the matching follow-up", "Tips for light users, an offer to help for active ones.", "email"),
      write("Hand the most active trials to sales", "With what they used most.", "crm"),
    ],
    agent: {
      name: "Trial follow-up",
      description: "Converts trials with timely, relevant follow-ups.",
      autonomyLevel: 3,
      objective: "More trials become paying customers.",
      context: "Activity comes from what the CRM records for the trial.",
      rules: ["Never offer discounts", "One email per trial per stage"],
      escalation: ["The trial is a large company", "The user asks about pricing for many seats"],
      success: ["Every ending trial got a follow-up", "Active trials handed to sales"],
    },
  },
  {
    slug: "library-churn-risk-outreach",
    title: "Churn-risk outreach",
    summary: "Spots customers showing signs of leaving and gets their account owner in touch before renewal.",
    department: "Customer Support",
    industries: ["SaaS & software"],
    trigger: "Every Monday",
    minutes: 20,
    steps: [
      read("Find accounts with churn signals", "Falling use, open complaints, renewal within 60 days.", "crm"),
      read("Check open tickets for each account", "Unresolved problems and tone.", "helpdesk"),
      decide("Rank the accounts at risk", "By revenue and how strong the signals are."),
      write("Create a save task for the owner", "With the signals and a suggested next step.", "projects"),
    ],
    agent: {
      name: "Churn risk",
      description: "Finds at-risk accounts each week and sets up save tasks.",
      autonomyLevel: 3,
      objective: "No renewal is lost without the owner knowing in time.",
      context: "Signals come from the CRM and help desk.",
      rules: ["Never contact the customer", "Never change the renewal or price"],
      escalation: ["One of the largest accounts shows strong signals"],
      success: ["Save tasks created for every at-risk account"],
    },
  },

  // ---------------------------------------------------------------- Marketplaces
  {
    slug: "library-listing-moderation",
    title: "New listing moderation",
    summary: "Checks every new listing against the listing rules and approves, fixes or holds it for review.",
    department: "Operations",
    industries: ["Marketplaces", "Property & rentals"],
    trigger: "A seller publishes a new listing",
    minutes: 3,
    steps: [
      read("Read the new listing", "Title, description, photos and price.", "ecommerce"),
      decide("Check it against the listing rules", "Prohibited items, misleading claims, contact details in text, price far off."),
      write("Approve or hold the listing", "Clear listings go live; others wait for review.", "ecommerce"),
      write("Tell the seller what to fix", "When a listing is held.", "email"),
    ],
    agent: {
      name: "Listing moderation",
      description: "Moderates new listings against the listing rules.",
      autonomyLevel: 3,
      objective: "Only listings that meet the rules go live, without slowing honest sellers down.",
      context: "The listing rules list prohibited items and required fields.",
      rules: ["Never delete a listing", "Hold, do not reject, when unsure"],
      escalation: ["The listing may involve illegal items or animal welfare", "The seller has had listings held before"],
      success: ["Every new listing approved or held within minutes"],
    },
  },
  {
    slug: "library-seller-onboarding",
    title: "Seller onboarding and verification",
    summary: "Walks new sellers through verification and their first listing, and flags sellers who stall.",
    department: "Operations",
    industries: ["Marketplaces"],
    trigger: "A new seller signs up",
    minutes: 12,
    steps: [
      read("Read the new seller's account", "Business details and verification status.", "crm"),
      write("Send the welcome and verification steps", "What is needed to start selling.", "email"),
      read("Check verification after three days", "Documents and payout details received.", "crm"),
      write("Remind sellers who have not finished", "One friendly reminder.", "email"),
      write("Flag sellers stuck after the reminder", "To the seller team.", "chat"),
    ],
    agent: {
      name: "Seller onboarding",
      description: "Gets new sellers verified and listing.",
      autonomyLevel: 3,
      objective: "New sellers finish verification and publish their first listing within a week.",
      context: "Verification decisions are made by the seller team.",
      rules: ["Never approve verification", "Never ask for documents beyond the checklist"],
      escalation: ["Details do not match", "The seller is a large business"],
      success: ["Every new seller welcomed and reminded once"],
    },
  },
  {
    slug: "library-dispute-handling",
    title: "Buyer and seller dispute handling",
    summary: "Gathers both sides of a dispute, the order and messages, and proposes an outcome for a person to approve.",
    department: "Customer Support",
    industries: ["Marketplaces", "Travel & booking", "E-commerce & D2C"],
    trigger: "A buyer or seller opens a dispute",
    minutes: 20,
    steps: [
      read("Read the dispute", "Who opened it, why, and what they want.", "helpdesk"),
      read("Get the order and payment", "Amount, dates and delivery status.", "payments"),
      write("Ask the other side for their account", "A neutral request with a deadline.", "email"),
      decide("Propose an outcome under the dispute policy", "Refund, partial refund or no action, with reasons."),
      write("Send the outcome once approved", "To both sides.", "helpdesk"),
    ],
    agent: {
      name: "Dispute handling",
      description: "Prepares disputes for a fair, fast decision.",
      autonomyLevel: 2,
      objective: "Disputes are decided fairly and quickly with all the facts in one place.",
      context: "A person approves every outcome.",
      rules: ["Stay neutral in every message", "Never move money without approval"],
      escalation: ["Either side threatens legal action", "The amount is above the approval limit"],
      success: ["Both sides heard", "Outcome proposed with reasons"],
    },
  },

  // ---------------------------------------------------------------- E-commerce & D2C
  {
    slug: "library-order-status",
    title: "Where-is-my-order replies",
    summary: "Answers order status questions with live tracking and handles late deliveries before customers ask twice.",
    department: "Customer Support",
    industries: ["E-commerce & D2C"],
    trigger: "A customer asks where their order is",
    minutes: 5,
    steps: [
      read("Read the question", "Order number or the customer's email.", "helpdesk"),
      read("Look up the order and shipment", "Status, carrier and tracking.", "ecommerce"),
      decide("Is the order late?", "Compare with the promised delivery date."),
      write("Reply with the status and tracking link", "Apologise and say what happens next if it is late.", "helpdesk"),
    ],
    agent: {
      name: "Order status",
      description: "Answers where-is-my-order questions with live tracking.",
      autonomyLevel: 4,
      objective: "Customers get an accurate order status within minutes.",
      context: "Delivery promises are shown on the order.",
      rules: ["Never promise a delivery date the carrier has not given", "Never offer compensation"],
      escalation: ["The order is more than 5 days late", "The parcel is marked delivered but the customer says it is not"],
      success: ["Question answered with the current status"],
    },
  },
  {
    slug: "library-returns",
    title: "Returns and exchanges",
    summary: "Approves returns within the return policy, sends the return label and tracks it back.",
    department: "Customer Support",
    industries: ["E-commerce & D2C"],
    trigger: "A customer asks to return or exchange an item",
    minutes: 8,
    steps: [
      read("Read the return request", "Item, reason and whether they want a refund or exchange.", "helpdesk"),
      read("Check the order", "Purchase date and item condition rules.", "ecommerce"),
      decide("Check the return policy", "Within the return window, item returnable."),
      write("Send the return instructions", "Label or address and what to include.", "email"),
      write("Update the order", "Mark a return as expected.", "ecommerce"),
    ],
    agent: {
      name: "Returns",
      description: "Handles returns and exchanges within the return policy.",
      autonomyLevel: 3,
      objective: "Eligible returns are approved the same day.",
      context: "Refunds happen when the return arrives, not before.",
      rules: ["Never refund before the item is back", "Final-sale items cannot be returned"],
      escalation: ["The item is damaged or faulty", "The customer has many returns"],
      success: ["Instructions sent", "Order marked as return expected"],
    },
  },
  {
    slug: "library-low-stock",
    title: "Low-stock reorder alerts",
    summary: "Watches stock levels and drafts a reorder for products about to run out.",
    department: "Operations",
    industries: ["E-commerce & D2C"],
    trigger: "Every morning",
    minutes: 15,
    steps: [
      read("Check stock levels", "Products below their reorder point.", "ecommerce"),
      decide("Work out the reorder quantity", "From the last 30 days of sales."),
      write("Draft the reorder", "Quantity per product in the purchasing sheet.", "spreadsheet"),
      write("Tell the buyer", "List of products and quantities to approve.", "chat"),
    ],
    agent: {
      name: "Low-stock alerts",
      description: "Spots products running low and drafts reorders.",
      autonomyLevel: 2,
      objective: "Best-sellers never go out of stock.",
      context: "Purchase orders are placed by a person.",
      rules: ["Never place an order", "Skip discontinued products"],
      escalation: ["A best-seller will run out within 3 days"],
      success: ["Reorder drafted for every product below its reorder point"],
    },
  },

  // ---------------------------------------------------------------- Media & publishing
  {
    slug: "library-subscriber-save",
    title: "Subscriber cancellation save",
    summary: "Answers cancellation requests with the right retention offer, and cancels cleanly when the reader still wants to go.",
    department: "Customer Support",
    industries: ["Media & publishing"],
    trigger: "A subscriber asks to cancel",
    minutes: 6,
    steps: [
      read("Read the cancellation request", "Reason if given.", "helpdesk"),
      read("Look up the subscription", "Plan, tenure and price.", "payments"),
      decide("Pick the retention option", "A pause, a cheaper plan, or none, by the retention rules."),
      write("Reply with the option or confirm the cancellation", "Always make cancelling easy.", "helpdesk"),
    ],
    agent: {
      name: "Subscriber retention",
      description: "Handles cancellations fairly, with a retention offer where the rules allow.",
      autonomyLevel: 3,
      objective: "Keep subscribers who would stay with a better option, and let others go without friction.",
      context: "Retention offers are set by the retention rules.",
      rules: ["Never refuse or delay a cancellation", "One offer only"],
      escalation: ["The subscriber is angry or mentions a complaint"],
      success: ["Every request answered the same day"],
    },
  },
  {
    slug: "library-comment-moderation",
    title: "Comment and content moderation",
    summary: "Reviews reader comments and submissions against the community rules and holds the ones that break them.",
    department: "Operations",
    industries: ["Media & publishing", "Marketplaces"],
    trigger: "A new comment or submission is posted",
    minutes: 2,
    steps: [
      read("Read the comment", "Text and the article it is on.", "documents"),
      decide("Check it against the community rules", "Abuse, spam, personal data, off-topic."),
      write("Publish or hold the comment", "Hold, do not delete, when unsure.", "documents"),
      write("Report repeat offenders", "To the community editor.", "chat"),
    ],
    agent: {
      name: "Comment moderation",
      description: "Moderates comments against the community rules.",
      autonomyLevel: 4,
      objective: "Conversations stay civil without slowing them down.",
      context: "Editors make final decisions on held comments.",
      rules: ["Never edit a reader's words", "Never ban accounts"],
      escalation: ["A comment contains threats or personal data", "Legal risk such as defamation"],
      success: ["Every comment published or held within minutes"],
    },
  },
  {
    slug: "library-advertiser-booking",
    title: "Advertiser booking and invoicing",
    summary: "Turns confirmed ad bookings into scheduled placements and invoices, and chases missing creative.",
    department: "Sales",
    industries: ["Media & publishing"],
    trigger: "An advertiser confirms a booking",
    minutes: 15,
    steps: [
      read("Read the confirmed booking", "Placements, dates and price.", "crm"),
      write("Schedule the placements", "In the ad planning sheet.", "spreadsheet"),
      write("Ask for missing creative", "With the specs and deadline.", "email"),
      write("Create the invoice", "For the agreed price and payment terms.", "accounting"),
    ],
    agent: {
      name: "Ad bookings",
      description: "Schedules ad bookings, chases creative and invoices them.",
      autonomyLevel: 3,
      objective: "Every confirmed booking runs on time and is invoiced.",
      context: "Prices come from the booking, never from the agent.",
      rules: ["Never change prices or dates", "Invoices above the approval limit wait for a person"],
      escalation: ["Creative is still missing two days before the run"],
      success: ["Placements scheduled", "Invoice created"],
    },
  },

  // ---------------------------------------------------------------- Agencies
  {
    slug: "library-client-report",
    title: "Weekly client performance report",
    summary: "Pulls each client's campaign numbers into a short weekly report for the account lead to send.",
    department: "Marketing",
    industries: ["Agencies"],
    trigger: "Every Friday",
    minutes: 45,
    steps: [
      read("Collect the week's campaign results", "Spend, results and cost per result per client.", "marketing"),
      read("Compare with last week and the target", "From the client tracker.", "spreadsheet"),
      decide("Write the three things that matter", "What changed, why, and what to do next."),
      write("Draft the report", "One page per client.", "documents"),
      write("Tell the account lead it is ready", "With the link.", "chat"),
    ],
    agent: {
      name: "Client reports",
      description: "Drafts weekly performance reports for each client.",
      autonomyLevel: 2,
      objective: "Account leads spend minutes, not hours, on weekly reports.",
      context: "The account lead reviews and sends every report.",
      rules: ["Never send to the client", "Only use numbers from the data"],
      escalation: ["Results are far below target"],
      success: ["A draft report for every client by Friday afternoon"],
    },
  },
  {
    slug: "library-timesheet-reminders",
    title: "Timesheet reminders",
    summary: "Reminds people with missing hours before the week closes and tells the manager who is still missing.",
    department: "Operations",
    industries: ["Agencies", "Professional services", "Recruitment & staffing"],
    trigger: "Every Friday afternoon",
    minutes: 20,
    steps: [
      read("Find missing or short timesheets", "Hours logged against expected hours.", "projects"),
      write("Remind each person", "Short, friendly message with their missing days.", "chat"),
      read("Check again on Monday morning", "Who has still not filled in.", "projects"),
      write("Tell the manager who is missing", "So invoicing is not delayed.", "chat"),
    ],
    agent: {
      name: "Timesheet reminders",
      description: "Makes sure hours are logged before invoicing.",
      autonomyLevel: 4,
      objective: "All hours are in before the invoicing run.",
      context: "Expected hours come from contracts in the project tool.",
      rules: ["Never fill in hours for someone"],
      escalation: ["Someone is missing a whole week"],
      success: ["Everyone reminded", "Manager told about anyone still missing"],
    },
  },
  {
    slug: "library-project-kickoff",
    title: "Project kickoff from a signed proposal",
    summary: "Turns a signed proposal into a project with tasks, a kickoff meeting and a client welcome.",
    department: "Operations",
    industries: ["Agencies", "Professional services"],
    trigger: "A proposal is signed",
    minutes: 30,
    steps: [
      read("Read the signed proposal", "Scope, deliverables, dates and team.", "esign"),
      write("Create the project and tasks", "From the scope and deliverables.", "projects"),
      write("Book the kickoff meeting", "With the client and the team.", "calendar"),
      write("Send the client welcome", "What happens next and who their contacts are.", "email"),
    ],
    agent: {
      name: "Project kickoff",
      description: "Sets up new projects as soon as the proposal is signed.",
      autonomyLevel: 3,
      objective: "Work starts the week the proposal is signed.",
      context: "The scope in the proposal is the source of truth.",
      rules: ["Never add scope beyond the proposal"],
      escalation: ["Dates in the proposal have already passed"],
      success: ["Project created", "Kickoff booked", "Client welcomed"],
    },
  },

  // ---------------------------------------------------------------- Recruitment & staffing
  {
    slug: "library-candidate-screening",
    title: "Candidate screening and interview scheduling",
    summary: "Screens new applicants against the must-haves and books interviews for the ones who fit.",
    department: "HR",
    industries: ["Recruitment & staffing"],
    trigger: "A new application arrives",
    minutes: 15,
    steps: [
      read("Read the application", "CV, cover letter and answers.", "hr"),
      decide("Check the must-have requirements", "Only the requirements in the vacancy, never personal traits."),
      write("Book interviews for candidates who fit", "Offer slots from the recruiter's calendar.", "calendar"),
      write("Mark the rest for recruiter review", "With the requirement that was not met.", "hr"),
    ],
    agent: {
      name: "Candidate screening",
      description: "Screens applicants on the vacancy's must-haves and books interviews.",
      autonomyLevel: 3,
      objective: "Good candidates get an interview within a day.",
      context: "Back-office only: a recruiter makes every rejection decision.",
      rules: ["Never reject a candidate", "Judge only on the vacancy's stated requirements", "Ignore age, gender, origin and other protected traits"],
      escalation: ["The vacancy has no clear must-haves"],
      success: ["Interviews booked for candidates who fit", "Others queued for a recruiter"],
    },
  },
  {
    slug: "library-contractor-timesheets",
    title: "Contractor timesheet approval and invoicing",
    summary: "Collects approved contractor hours each week and drafts the client invoices from them.",
    department: "Finance",
    industries: ["Recruitment & staffing", "Agencies"],
    trigger: "Every Monday",
    minutes: 30,
    steps: [
      read("Collect last week's timesheets", "Hours per contractor and client.", "spreadsheet"),
      write("Ask clients to approve open timesheets", "With the hours to approve.", "email"),
      read("Check which timesheets are approved", "By Wednesday.", "spreadsheet"),
      write("Draft invoices for approved hours", "At the agreed rates.", "accounting"),
    ],
    agent: {
      name: "Contractor invoicing",
      description: "Turns approved contractor hours into client invoices.",
      autonomyLevel: 3,
      objective: "Every approved hour is invoiced the same week.",
      context: "Rates come from the client agreement.",
      rules: ["Never invoice unapproved hours", "Never change rates"],
      escalation: ["A client disputes hours"],
      success: ["Invoices drafted for all approved hours"],
    },
  },

  // ---------------------------------------------------------------- Online education
  {
    slug: "library-enrolment",
    title: "Enrolment and payment-plan setup",
    summary: "Confirms new enrolments, sets up the payment plan and gives students their course access.",
    department: "Operations",
    industries: ["Online education"],
    trigger: "A student enrols",
    minutes: 10,
    steps: [
      read("Read the enrolment", "Course, start date and payment choice.", "forms"),
      write("Set up the payment plan", "Instalments as chosen.", "payments"),
      write("Send the welcome and access details", "Start date and how to log in.", "email"),
      write("Add the student to the course list", "For the course team.", "spreadsheet"),
    ],
    agent: {
      name: "Enrolment",
      description: "Completes new enrolments end to end.",
      autonomyLevel: 3,
      objective: "Students have access and a payment plan within an hour of enrolling.",
      context: "Payment plan options are set per course.",
      rules: ["Never offer discounts or extra instalments"],
      escalation: ["The course is full", "The payment setup fails"],
      success: ["Payment plan set up", "Welcome sent"],
    },
  },
  {
    slug: "library-student-support",
    title: "Student support answers",
    summary: "Answers common student questions from the course handbook and routes the rest to tutors.",
    department: "Customer Support",
    industries: ["Online education"],
    trigger: "A student sends a question",
    minutes: 5,
    steps: [
      read("Read the question", "And the student's course.", "helpdesk"),
      read("Search the course handbook", "Deadlines, rules and how-tos.", "documents"),
      decide("Can the handbook answer it?", "Only answer what the handbook covers."),
      write("Reply or route to a tutor", "Quote the handbook section when answering.", "helpdesk"),
    ],
    agent: {
      name: "Student support",
      description: "Answers handbook questions and routes the rest.",
      autonomyLevel: 4,
      objective: "Students get answers to routine questions in minutes.",
      context: "Tutors handle anything about grades or course content.",
      rules: ["Never comment on grades", "Never grant extensions"],
      escalation: ["The student mentions wellbeing or a personal crisis"],
      success: ["Routine questions answered", "Others routed to a tutor"],
    },
  },
  {
    slug: "library-certificates",
    title: "Completion certificates",
    summary: "Issues certificates to students who completed their course and sends them by email.",
    department: "Operations",
    industries: ["Online education"],
    trigger: "Every evening",
    minutes: 5,
    steps: [
      read("Find students who completed a course today", "From the course records.", "spreadsheet"),
      write("Create each certificate", "From the certificate template.", "documents"),
      write("Email the certificate", "With congratulations and the next course.", "email"),
    ],
    agent: {
      name: "Certificates",
      description: "Issues completion certificates the day students finish.",
      autonomyLevel: 4,
      objective: "Every student who completes a course gets their certificate the same day.",
      context: "Completion is recorded by the course team.",
      rules: ["Only issue for completions in the records"],
      escalation: ["A student's name is missing or unclear"],
      success: ["Certificates created and sent"],
    },
  },

  // ---------------------------------------------------------------- Travel & booking
  {
    slug: "library-booking-changes",
    title: "Booking change requests",
    summary: "Handles date and name changes within the change rules and quotes any fee before changing.",
    department: "Customer Support",
    industries: ["Travel & booking"],
    trigger: "A customer asks to change a booking",
    minutes: 10,
    steps: [
      read("Read the change request", "What they want changed.", "helpdesk"),
      read("Look up the booking", "Dates, fare rules and supplier.", "ecommerce"),
      decide("Check the change rules", "Allowed changes and the fee."),
      write("Quote the change and fee", "Ask the customer to confirm.", "helpdesk"),
      write("Make the change once confirmed", "And send the updated confirmation.", "ecommerce"),
    ],
    agent: {
      name: "Booking changes",
      description: "Handles booking changes within the change rules.",
      autonomyLevel: 3,
      objective: "Routine changes are done in one exchange.",
      context: "Supplier rules decide what can change.",
      rules: ["Never change a booking before the customer confirms the fee", "Never waive fees"],
      escalation: ["The supplier does not allow the change", "The trip starts within 48 hours"],
      success: ["Change quoted and, once confirmed, made"],
    },
  },
  {
    slug: "library-supplier-reconciliation",
    title: "Supplier invoice reconciliation",
    summary: "Matches supplier invoices to bookings and flags mismatches before they are paid.",
    department: "Finance",
    industries: ["Travel & booking", "E-commerce & D2C"],
    trigger: "A supplier invoice arrives",
    minutes: 15,
    steps: [
      read("Read the supplier invoice", "Lines, amounts and references.", "accounting"),
      read("Find the matching bookings or orders", "By reference and date.", "spreadsheet"),
      decide("Compare amounts and quantities", "Flag any difference above the tolerance."),
      write("Mark matched invoices ready to pay", "Mismatches go to finance with the difference.", "accounting"),
    ],
    agent: {
      name: "Supplier reconciliation",
      description: "Checks supplier invoices against bookings before payment.",
      autonomyLevel: 3,
      objective: "Only correct supplier invoices get paid.",
      context: "Finance pays; the agent only checks.",
      rules: ["Never pay an invoice", "Never change invoice amounts"],
      escalation: ["The difference is above the tolerance", "The supplier is new"],
      success: ["Every invoice matched or flagged"],
    },
  },

  // ---------------------------------------------------------------- Property & rentals
  {
    slug: "library-viewing-scheduling",
    title: "Viewing scheduling",
    summary: "Answers viewing requests, offers open slots and confirms viewings in the agent's calendar.",
    department: "Sales",
    industries: ["Property & rentals"],
    trigger: "Someone asks to view a property",
    minutes: 8,
    steps: [
      read("Read the viewing request", "Which property and when.", "email"),
      read("Check open viewing slots", "In the agent's calendar.", "calendar"),
      write("Offer two or three slots", "With the address and what to bring.", "email"),
      write("Book the chosen slot", "And send a reminder the day before.", "calendar"),
    ],
    agent: {
      name: "Viewing scheduling",
      description: "Books property viewings without back-and-forth.",
      autonomyLevel: 4,
      objective: "Every viewing request gets slots within the hour.",
      context: "Slots come from the agent's calendar.",
      rules: ["Never double-book", "Never confirm a property is still available without checking"],
      escalation: ["The property is under offer"],
      success: ["Slots offered", "Chosen viewing booked"],
    },
  },
  {
    slug: "library-maintenance-requests",
    title: "Tenant maintenance requests",
    summary: "Logs each maintenance request, sets its urgency and books the right contractor.",
    department: "Operations",
    industries: ["Property & rentals"],
    trigger: "A tenant reports a problem",
    minutes: 12,
    steps: [
      read("Read the request", "Property, problem and photos.", "helpdesk"),
      decide("Set the urgency", "Emergency (water, gas, no heat), urgent, or routine."),
      write("Create the job", "With urgency and access details.", "projects"),
      write("Ask the right contractor for a slot", "From the contractor list.", "email"),
      write("Tell the tenant what happens next", "And when.", "helpdesk"),
    ],
    agent: {
      name: "Maintenance requests",
      description: "Turns maintenance requests into booked jobs.",
      autonomyLevel: 3,
      objective: "Tenants know within an hour what is being done.",
      context: "Contractors and their trades come from the contractor list.",
      rules: ["Never approve costs above the repair limit"],
      escalation: ["Any emergency such as a leak, gas smell or no heating", "The quote is above the repair limit"],
      success: ["Job created", "Contractor asked", "Tenant told"],
    },
  },
  {
    slug: "library-rent-arrears",
    title: "Rent arrears reminders",
    summary: "Reminds tenants about late rent on a set schedule and flags arrears to the property manager.",
    department: "Finance",
    industries: ["Property & rentals"],
    trigger: "Rent is three days late",
    minutes: 10,
    steps: [
      read("Find late rent payments", "Tenant, property and amount.", "accounting"),
      read("Check for a payment just received", "Avoid reminding someone who has paid.", "payments"),
      write("Send the reminder", "Polite, with the amount and how to pay.", "email"),
      write("Flag arrears over 14 days", "To the property manager.", "chat"),
    ],
    agent: {
      name: "Rent reminders",
      description: "Sends late-rent reminders and flags arrears.",
      autonomyLevel: 3,
      objective: "Late rent is paid without awkward chasing.",
      context: "Next steps beyond reminders are decided by the property manager.",
      rules: ["Never mention eviction or legal steps", "One reminder per week"],
      escalation: ["The tenant reports hardship", "Arrears exceed one month's rent"],
      success: ["Reminders sent", "Long arrears flagged"],
    },
  },

  // ---------------------------------------------------------------- Fintech & insurance
  {
    slug: "library-claims-intake",
    title: "Claims intake triage",
    summary: "Checks new claims are complete, routes them to the right handler, and requests what is missing. It never decides a claim.",
    department: "Operations",
    industries: ["Fintech & insurance"],
    trigger: "A new claim is submitted",
    minutes: 15,
    steps: [
      read("Read the new claim", "Policy, incident and attachments.", "forms"),
      decide("Check the claim is complete", "Required fields and documents for this claim type."),
      write("Request missing information", "Exactly what is missing and why.", "email"),
      write("Route complete claims to a handler", "By claim type and value.", "helpdesk"),
    ],
    agent: {
      name: "Claims intake",
      description: "Makes sure claims arrive complete with the right handler.",
      autonomyLevel: 3,
      objective: "Handlers only receive complete claims, routed correctly.",
      context: "Back-office only: handlers decide every claim.",
      rules: ["Never accept, reject or value a claim", "Never comment on cover"],
      escalation: ["Fraud indicators", "The claimant is vulnerable or distressed"],
      success: ["Complete claims routed", "Missing items requested"],
    },
  },
  {
    slug: "library-verification-follow-up",
    title: "Account verification follow-up",
    summary: "Follows up customers whose account verification is stuck and tells compliance which files need review.",
    department: "Operations",
    industries: ["Fintech & insurance"],
    trigger: "A verification has been pending for two days",
    minutes: 10,
    steps: [
      read("Find verifications stuck in pending", "And what is missing.", "crm"),
      write("Remind the customer", "What to upload and how.", "email"),
      read("Check what came back", "Documents now provided.", "documents"),
      write("Send complete files to compliance", "For review; the agent never approves.", "chat"),
    ],
    agent: {
      name: "Verification follow-up",
      description: "Unblocks stuck account verifications.",
      autonomyLevel: 3,
      objective: "Verifications are complete within a week.",
      context: "Back-office only: compliance approves every verification.",
      rules: ["Never approve or reject a verification", "Never ask for data the checklist does not require"],
      escalation: ["Documents look inconsistent", "The customer appears on a watch list"],
      success: ["Reminders sent", "Complete files with compliance"],
    },
  },

  // ---------------------------------------------------------------- Professional services
  {
    slug: "library-client-intake",
    title: "Client intake and engagement letter",
    summary: "Collects a new client's details, prepares the engagement letter for signing, and opens the client file.",
    department: "Operations",
    industries: ["Professional services"],
    trigger: "A new client is accepted",
    minutes: 25,
    steps: [
      read("Read the new client details", "Contact, entity and the work agreed.", "crm"),
      write("Prepare the engagement letter", "From the standard template and the agreed scope.", "documents"),
      write("Send it for signature", "To the client contact.", "esign"),
      write("Open the client file", "With the signed letter once it is back.", "documents"),
    ],
    agent: {
      name: "Client intake",
      description: "Gets new clients signed and filed.",
      autonomyLevel: 2,
      objective: "New clients are engaged properly within a day.",
      context: "Back-office only: a partner checks every letter before it is sent.",
      rules: ["Never change fees or scope in the template", "Never give advice"],
      escalation: ["The client is in a sector that needs extra checks"],
      success: ["Letter prepared and sent", "Client file opened"],
    },
  },
];

// The migration that holds the library (regenerate it after editing the list).
export const LIBRARY_MIGRATION = "20261001000021_playbook_library.sql";

// The playbook as the playbooks table stores it.
export function libraryRow(p: LibraryPlaybook) {
  return {
    slug: p.slug,
    title: p.title,
    summary: p.summary,
    department: p.department,
    industries: p.industries,
    capabilities: [...new Set(p.steps.map((s) => s.capability).filter((c): c is string => Boolean(c)))],
    trigger: p.trigger,
    steps: p.steps,
    agent: {
      name: p.agent.name,
      description: p.agent.description,
      autonomyLevel: p.agent.autonomyLevel,
      instructions: {
        objective: p.agent.objective,
        context: p.agent.context,
        rules: p.agent.rules,
        steps: p.steps.map((s) => (s.detail ? `${s.title}: ${s.detail}` : s.title)),
        escalationConditions: p.agent.escalation,
        successConditions: p.agent.success,
      },
      successCriteria: p.agent.success,
    },
    estimated_minutes_per_occurrence: p.minutes,
  };
}

const lit = (s: string) => `'${s.replaceAll("'", "''")}'`;
const arr = (xs: string[]) => `array[${xs.map(lit).join(", ")}]::text[]`;

// The migration that writes the library: published, and never over a playbook that exists.
export function librarySql(): string {
  const rows = PLAYBOOK_LIBRARY.map((p) => {
    const r = libraryRow(p);
    return `  (${[
      lit(r.slug),
      lit(r.title),
      lit(r.summary),
      lit(r.department),
      arr(r.industries),
      arr(r.capabilities),
      lit(r.trigger),
      `${lit(JSON.stringify(r.steps))}::jsonb`,
      `${lit(JSON.stringify(r.agent))}::jsonb`,
      String(r.estimated_minutes_per_occurrence),
      "'published'",
    ].join(", ")})`;
  });
  return `-- Generated by packages/integrations (pnpm --filter @autonomos/integrations playbooks:sql) from
-- src/playbook-library.ts. Do not edit by hand. Existing playbooks (same slug) are left alone.
insert into public.playbooks (slug, title, summary, department, industries, capabilities, trigger, steps, agent, estimated_minutes_per_occurrence, status)
values
${rows.join(",\n")}
on conflict (slug) do nothing;
`;
}
